// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujvzwdaxrokfghnswwdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdnp3ZGF4cm9rZmdobnN3d2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTI5NjgsImV4cCI6MjA2NTQ2ODk2OH0.zDUW_IDbgML0-DEtqKsT_JpGoTCQXCuEymLuuCty8xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);